#!/usr/bin/env python3
"""First-run / new-machine setup for Jugoo.

Installs system packages, XDG identity (``jugoo`` wrapper), Hyprland integration
(binds, window rules, popup placement, autostart) and an initial theme export.

Usage (from the Jugoo checkout)::

    python3 acomodador.py
    python3 acomodador.py --dry-run
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from shell.config import ACTIVE_THEME, HYPRLAND_THEME_EXPORT_PATH  # noqa: E402
from shell.desktop_install import install_identity  # noqa: E402
from shell.identity import project_root  # noqa: E402
from shell.ui.theme import export_hypr_theme, load_theme  # noqa: E402

HYPR_CONFIG_HOME = Path(
    os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")
) / "hypr"
HYPR_LUA_DIR = HYPR_CONFIG_HOME / "config"
HYPRLAND_LUA = HYPR_CONFIG_HOME / "hyprland.lua"
PACKAGING_HYPR = ROOT / "packaging" / "hyprland"
REQUIREMENTS = ROOT / "system-requirements.txt"

# Pacman packages required for a working Jugoo + Hyprland integration.
REQUIRED_PACKAGES = (
    "python-gobject",
    "python-cairo",
    "gtk3",
    "gtk-layer-shell",
    "wtype",
    "hyprpolkitagent",
)

OPTIONAL_PACKAGES = (
    "strawberry",
)

MARKER_BEGIN = "-- >>> jugoo-acomodador begin"
MARKER_END = "-- >>> jugoo-acomodador end"

JUGOO_REQUIRE_BLOCK = f"""{MARKER_BEGIN}
require("config.jugoo_binds")
require("config.jugoo_windowrules")
require("config.jugoo_popup_place")
require("config.jugoo_autostart")
-- Theme colors/blur/rounding from themes/*.toml (regenerated by the shell).
require("config.jugoo_theme_generated").apply()
{MARKER_END}
"""

MANAGED_LUA = (
    "jugoo_binds.lua",
    "jugoo_windowrules.lua",
    "jugoo_popup_place.lua",
    "jugoo_autostart.lua",
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Configure Jugoo on a new machine")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print actions without writing or installing packages",
    )
    parser.add_argument(
        "--skip-packages",
        action="store_true",
        help="Skip pacman installs (identity + Hyprland only)",
    )
    parser.add_argument(
        "--with-optional",
        action="store_true",
        help="Also install optional packages (e.g. strawberry)",
    )
    args = parser.parse_args(argv)

    print("Jugoo acomodador")
    print(f"  checkout: {project_root()}")
    print(f"  hypr:     {HYPR_CONFIG_HOME}")
    print()

    if not args.skip_packages:
        _install_packages(args.with_optional, dry_run=args.dry_run)
        _enable_hyprpolkitagent(dry_run=args.dry_run)
    else:
        print("• packages: skipped")

    if args.dry_run:
        print("• identity: would run python3 -m shell --install")
    else:
        print("• identity: installing XDG wrapper / .desktop / task-watcher…")
        install_identity()

    _install_hyprland_snippets(dry_run=args.dry_run)
    _ensure_hyprland_lua(dry_run=args.dry_run)
    _export_theme(dry_run=args.dry_run)

    print()
    print("Listo.")
    print("  Arranque:  jugoo")
    print("  Dev:       python3 -m shell")
    print("  Acciones:  jugoo action list")
    print("  Recarga Hyprland: hyprctl reload")
    print()
    print(
        "Si ya tenías binds de Jugoo en config/binds.lua, quita los duplicados "
        "para no registrar la misma tecla dos veces."
    )
    return 0


def _install_packages(with_optional: bool, *, dry_run: bool) -> None:
    packages = list(REQUIRED_PACKAGES)
    if with_optional:
        packages.extend(OPTIONAL_PACKAGES)
    # Also pick up any `pacman -S` lines from system-requirements.txt.
    packages.extend(_packages_from_requirements())
    # Preserve order, drop dupes.
    ordered: list[str] = []
    seen: set[str] = set()
    for name in packages:
        if name not in seen:
            seen.add(name)
            ordered.append(name)

    print(f"• packages: {' '.join(ordered)}")
    cmd = ["sudo", "pacman", "-S", "--needed", "--noconfirm", *ordered]
    if dry_run:
        print(f"  dry-run: {' '.join(cmd)}")
        return
    result = subprocess.run(cmd, check=False)
    if result.returncode != 0:
        print(
            "  aviso: pacman falló (¿sudo?). Instala a mano lo de system-requirements.txt.",
            file=sys.stderr,
        )


def _packages_from_requirements() -> list[str]:
    if not REQUIREMENTS.is_file():
        return []
    found: list[str] = []
    for line in REQUIREMENTS.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped.startswith("sudo pacman -S"):
            continue
        # Drop the command prefix and flags.
        rest = stripped.split("pacman -S", 1)[-1].strip()
        for token in rest.split():
            if token.startswith("-"):
                continue
            if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9@._+-]*", token):
                found.append(token)
    return found


def _enable_hyprpolkitagent(*, dry_run: bool) -> None:
    cmd = ["systemctl", "--user", "enable", "--now", "hyprpolkitagent.service"]
    print("• polkit agent: hyprpolkitagent")
    if dry_run:
        print(f"  dry-run: {' '.join(cmd)}")
        return
    result = subprocess.run(cmd, check=False, capture_output=True, text=True)
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()
        print(f"  aviso: no se pudo activar hyprpolkitagent ({detail or 'error'})")


def _install_hyprland_snippets(*, dry_run: bool) -> None:
    if not PACKAGING_HYPR.is_dir():
        print("• hypr snippets: packaging/hyprland missing", file=sys.stderr)
        return
    print(f"• hypr snippets → {HYPR_LUA_DIR}")
    if dry_run:
        for name in MANAGED_LUA:
            print(f"  dry-run: copy {name}")
        return
    HYPR_LUA_DIR.mkdir(parents=True, exist_ok=True)
    for name in MANAGED_LUA:
        src = PACKAGING_HYPR / name
        if not src.is_file():
            print(f"  aviso: falta {src}", file=sys.stderr)
            continue
        dest = HYPR_LUA_DIR / name
        shutil.copy2(src, dest)
        print(f"  wrote {dest}")


def _ensure_hyprland_lua(*, dry_run: bool) -> None:
    print(f"• hyprland.lua: {HYPRLAND_LUA}")
    if dry_run:
        print("  dry-run: ensure jugoo require block")
        return

    HYPR_CONFIG_HOME.mkdir(parents=True, exist_ok=True)
    if not HYPRLAND_LUA.is_file():
        content = (
            "-- Generated by Jugoo acomodador for a minimal Hyprland entry.\n"
            "-- Merge with your full CachyOS/Hyprland config as needed.\n\n"
            f"{JUGOO_REQUIRE_BLOCK}\n"
        )
        HYPRLAND_LUA.write_text(content, encoding="utf-8")
        print("  created minimal hyprland.lua with Jugoo requires")
        return

    text = HYPRLAND_LUA.read_text(encoding="utf-8")
    if MARKER_BEGIN in text and MARKER_END in text:
        pattern = re.compile(
            re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END),
            re.DOTALL,
        )
        updated = pattern.sub(JUGOO_REQUIRE_BLOCK.strip(), text)
        if updated != text:
            HYPRLAND_LUA.write_text(updated, encoding="utf-8")
            print("  refreshed jugoo require block")
        else:
            print("  jugoo require block already up to date")
        return

    # Append managed block; keep any existing theme require if present.
    addition = "\n" + JUGOO_REQUIRE_BLOCK
    if "jugoo_theme_generated" in text:
        print(
            "  aviso: ya hay referencias a jugoo_theme_generated; "
            "revisa duplicados tras el bloque añadido."
        )
    HYPRLAND_LUA.write_text(text.rstrip() + "\n" + addition + "\n", encoding="utf-8")
    print("  appended jugoo require block")


def _export_theme(*, dry_run: bool) -> None:
    theme_path = ROOT / "themes" / f"{ACTIVE_THEME}.toml"
    dest = Path(HYPRLAND_THEME_EXPORT_PATH).expanduser()
    print(f"• theme export: {theme_path.name} → {dest}")
    if dry_run:
        print("  dry-run: export_hypr_theme")
        return
    if not theme_path.is_file():
        print(f"  aviso: no existe {theme_path}", file=sys.stderr)
        return
    try:
        theme = load_theme(theme_path)
        export_hypr_theme(theme, dest)
        print("  theme written (reload Hyprland / start Jugoo to apply live)")
    except Exception as error:  # noqa: BLE001
        print(f"  aviso: no se pudo exportar el tema ({error})", file=sys.stderr)


if __name__ == "__main__":
    raise SystemExit(main())
