"""Declarative settings catalog. UI and persistence consume this, not hardcoded widgets."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Callable, Literal

from .. import config as shell_config
from .task_taxonomy import default_categories_json, default_priorities_json
from ..ui.workspace_accents import default_accent_colors_json

SettingType = Literal["bool", "int", "float", "string", "choice", "path"]
ApplyMode = Literal["live", "reload", "restart"]

APPLY_LIVE: ApplyMode = "live"
APPLY_RELOAD: ApplyMode = "reload"
APPLY_RESTART: ApplyMode = "restart"


class CategoryId(str, Enum):
    GENERAL = "general"
    APARIENCIA = "apariencia"
    TEMA = "tema"
    BARRA = "barra"
    WIDGETS = "widgets"
    LAYOUT = "layout"
    POPUPS = "popups"
    NOTIFICACIONES = "notificaciones"
    MULTIMEDIA = "multimedia"
    ESTADISTICAS = "estadisticas"
    IA = "ia"
    MODO_NOCHE = "modo_noche"
    COMPORTAMIENTO = "comportamiento"
    AVANZADO = "avanzado"


CATEGORY_META: dict[CategoryId, tuple[str, str]] = {
    CategoryId.GENERAL: ("General", "Preferencias básicas de Jugoo"),
    CategoryId.APARIENCIA: ("Apariencia", "Densidad, tipografía y superficies"),
    CategoryId.TEMA: ("Tema", "Identidad visual (separada de preferencias)"),
    CategoryId.BARRA: ("Barra", "Posición, márgenes y módulos de la barra"),
    CategoryId.WIDGETS: ("Widgets", "Opciones por módulo"),
    CategoryId.LAYOUT: ("Layout", "Orden y visibilidad (base del editor visual)"),
    CategoryId.POPUPS: ("Popups y OSD", "Paneles, overlays y OSD"),
    CategoryId.NOTIFICACIONES: ("Notificaciones", "Toasts, sonido e historial"),
    CategoryId.MULTIMEDIA: ("Multimedia", "MPRIS, artwork y visualizador"),
    CategoryId.ESTADISTICAS: ("Estadísticas", "CPU, RAM, GPU y sensores"),
    CategoryId.IA: ("IA", "llama-cli y recordatorios inteligentes"),
    CategoryId.MODO_NOCHE: ("Modo noche", "Luz cálida de pantalla"),
    CategoryId.COMPORTAMIENTO: ("Comportamiento", "Timers y políticas generales"),
    CategoryId.AVANZADO: ("Avanzado", "Rendimiento e integraciones"),
}


@dataclass(frozen=True)
class SettingDef:
    key: str
    category: CategoryId
    label: str
    description: str
    value_type: SettingType
    default: Any
    config_attr: str | None = None
    apply: ApplyMode = APPLY_LIVE
    minimum: float | None = None
    maximum: float | None = None
    step: float | None = None
    choices: tuple[tuple[str, str], ...] = ()
    tier: Literal["A", "B", "C"] = "A"
    section: str = ""
    unit: str = ""


def _clock_format_choices() -> tuple[tuple[str, str], ...]:
    return (
        ("%I:%M %p", "12 h (03:45 PM)"),
        ("%H:%M", "24 h (15:45)"),
        ("%I:%M", "12 h sin AM/PM"),
        ("%H:%M:%S", "24 h con segundos"),
    )


def _date_format_choices() -> tuple[tuple[str, str], ...]:
    return (
        ("%a · %d %b", "Lun · 08 sep"),
        ("%A %d %B", "Lunes 08 septiembre"),
        ("%d/%m/%Y", "08/09/2026"),
        ("%Y-%m-%d", "2026-09-08"),
    )


def build_settings_catalog() -> tuple[SettingDef, ...]:
    """User-facing catalog. Internal D-tier knobs stay out of this list on purpose."""
    return (
        # —— Tema ——
        SettingDef(
            key="tema.active",
            category=CategoryId.TEMA,
            label="Tema activo",
            description="Identidad visual de Jugoo (TOML en themes/).",
            value_type="choice",
            default=shell_config.ACTIVE_THEME,
            config_attr="ACTIVE_THEME",
            apply=APPLY_LIVE,
            choices=(),  # filled at runtime from ThemeManager
            tier="A",
            section="Catálogo",
        ),
        # —— SDDM (greeter). Privileged apply is explicit via UI/CLI buttons. ——
        SettingDef(
            key="sddm.enabled",
            category=CategoryId.TEMA,
            label="Administrar pantalla de inicio (SDDM)",
            description=(
                "Si está activo, Jugoo administra y activa el tema SDDM oficial. "
                "Los cambios no se aplican solos: usa Aplicar / Restaurar."
            ),
            value_type="bool",
            default=False,
            apply=APPLY_LIVE,
            tier="A",
            section="SDDM",
        ),
        SettingDef(
            key="sddm.background_path",
            category=CategoryId.TEMA,
            label="Fondo de SDDM",
            description=(
                "Imagen JPG/PNG (rutas con espacios o Unicode permitidas). "
                "Jugoo la copia al tema; SDDM no lee tu home directamente."
            ),
            value_type="path",
            default="",
            apply=APPLY_LIVE,
            tier="A",
            section="SDDM",
        ),
        SettingDef(
            key="sddm.background_dim",
            category=CategoryId.TEMA,
            label="Oscurecimiento del fondo",
            description="Opacidad de la capa oscura sobre el fondo (0 = nada, 1 = opaco).",
            value_type="float",
            default=0.45,
            minimum=0.0,
            maximum=1.0,
            step=0.05,
            apply=APPLY_LIVE,
            tier="A",
            section="SDDM",
        ),
        SettingDef(
            key="sddm.background_fill",
            category=CategoryId.TEMA,
            label="Escalado del fondo",
            description="Recortar para llenar (crop) o ajustar completo (fit).",
            value_type="choice",
            default="crop",
            choices=(("crop", "Recortar (crop)"), ("fit", "Ajustar (fit)")),
            apply=APPLY_LIVE,
            tier="A",
            section="SDDM",
        ),
        SettingDef(
            key="sddm.show_avatar",
            category=CategoryId.TEMA,
            label="Mostrar avatar",
            description="Muestra el marcador de avatar en el formulario de login.",
            value_type="bool",
            default=True,
            apply=APPLY_LIVE,
            tier="A",
            section="SDDM",
        ),
        SettingDef(
            key="sddm.show_clock",
            category=CategoryId.TEMA,
            label="Mostrar reloj",
            description="Reloj y fecha encima del formulario.",
            value_type="bool",
            default=True,
            apply=APPLY_LIVE,
            tier="A",
            section="SDDM",
        ),
        SettingDef(
            key="sddm.form_opacity",
            category=CategoryId.TEMA,
            label="Opacidad del formulario",
            description="Transparencia del panel de login.",
            value_type="float",
            default=0.88,
            minimum=0.2,
            maximum=1.0,
            step=0.05,
            apply=APPLY_LIVE,
            tier="A",
            section="SDDM",
        ),
        SettingDef(
            key="sddm.form_radius",
            category=CategoryId.TEMA,
            label="Redondeo del formulario",
            description="Radio en px. Vacío/0 usa el radio del tema Jugoo activo al aplicar.",
            value_type="int",
            default=12,
            minimum=0,
            maximum=48,
            step=1,
            unit="px",
            apply=APPLY_LIVE,
            tier="B",
            section="SDDM",
        ),
        SettingDef(
            key="general.avatar_path",
            category=CategoryId.GENERAL,
            label="Avatar de usuario",
            description=(
                "Imagen circular del panel de usuario. "
                "Al elegirla, Jugoo guarda una copia en assets/usuario. "
                "Si aún no hay copia, se intenta ~/.face y ~/.face.icon."
            ),
            value_type="path",
            default="",
            apply=APPLY_LIVE,
            tier="A",
            section="Perfil",
        ),
        SettingDef(
            key="general.machine_image_path",
            category=CategoryId.GENERAL,
            label="Foto de la PC",
            description=(
                "Imagen de esta máquina en el panel de usuario. "
                "Al elegirla, Jugoo guarda una copia en assets/pc."
            ),
            value_type="path",
            default="",
            apply=APPLY_LIVE,
            tier="A",
            section="Perfil",
        ),
        SettingDef(
            key="general.profile_fields_json",
            category=CategoryId.GENERAL,
            label="Datos personalizados",
            description="Pares título/valor mostrados en el panel de usuario.",
            value_type="string",
            default="[]",
            apply=APPLY_LIVE,
            tier="A",
            section="Datos personalizados",
        ),
        # —— General / Apariencia ——
        SettingDef(
            key="apariencia.ui_font",
            category=CategoryId.APARIENCIA,
            label="Fuente de la interfaz",
            description="Familia tipográfica de Jugoo. Vacío usa la del sistema.",
            value_type="choice",
            default="",
            apply=APPLY_LIVE,
            choices=(),  # filled at runtime from system fonts
            tier="A",
            section="Tipografía",
        ),
        SettingDef(
            key="apariencia.animations_follow_theme",
            category=CategoryId.APARIENCIA,
            label="Respetar animaciones del tema",
            description="Si está activo, duración y enable vienen del tema.",
            value_type="bool",
            default=True,
            apply=APPLY_LIVE,
            tier="B",
            section="Animación",
        ),
        # —— Barra ——
        SettingDef(
            key="barra.top_margin",
            category=CategoryId.BARRA,
            label="Margen superior",
            description="Inset de la barra respecto al borde del monitor.",
            value_type="int",
            default=shell_config.TOP_MARGIN,
            config_attr="TOP_MARGIN",
            apply=APPLY_RELOAD,
            minimum=0,
            maximum=48,
            step=1,
            tier="B",
            section="Geometría",
            unit="px",
        ),
        SettingDef(
            key="barra.active_window_width",
            category=CategoryId.BARRA,
            label="Ancho ventana activa",
            description="Ancho estable del bloque de ventana activa + media.",
            value_type="int",
            default=shell_config.ACTIVE_WINDOW_WIDTH,
            config_attr="ACTIVE_WINDOW_WIDTH",
            apply=APPLY_RELOAD,
            minimum=160,
            maximum=480,
            step=8,
            tier="A",
            section="Geometría",
            unit="px",
        ),
        # —— Widgets ——
        SettingDef(
            key="widgets.clock_time_format",
            category=CategoryId.WIDGETS,
            label="Formato de hora",
            description="strftime para el reloj de la barra.",
            value_type="choice",
            default=shell_config.CLOCK_TIME_FORMAT,
            config_attr="CLOCK_TIME_FORMAT",
            apply=APPLY_LIVE,
            choices=_clock_format_choices(),
            tier="A",
            section="Reloj",
        ),
        SettingDef(
            key="widgets.clock_date_format",
            category=CategoryId.WIDGETS,
            label="Formato de fecha",
            description="strftime para la fecha compacta bajo la hora.",
            value_type="choice",
            default=shell_config.CLOCK_DATE_FORMAT,
            config_attr="CLOCK_DATE_FORMAT",
            apply=APPLY_LIVE,
            choices=_date_format_choices(),
            tier="A",
            section="Reloj",
        ),
        SettingDef(
            key="widgets.pinned_apps_limit",
            category=CategoryId.WIDGETS,
            label="Apps ancladas visibles",
            description="Huecos del dock en la barra antes del overflow.",
            value_type="int",
            default=shell_config.PINNED_APPS_VISIBLE_LIMIT,
            config_attr="PINNED_APPS_VISIBLE_LIMIT",
            apply=APPLY_RELOAD,
            minimum=3,
            maximum=16,
            step=1,
            tier="A",
            section="Apps ancladas",
        ),
        SettingDef(
            key="widgets.workspace_accent_colors_json",
            category=CategoryId.WIDGETS,
            label="Colores de workspaces especiales",
            description=(
                "Color de cada workspace especial o con nombre (special, minimizados, gaming…). "
                "Se detectan desde Hypr y la sesión activa."
            ),
            value_type="string",
            default=default_accent_colors_json(),
            apply=APPLY_LIVE,
            tier="A",
            section="Workspaces",
        ),
        SettingDef(
            key="widgets.task_categories_json",
            category=CategoryId.WIDGETS,
            label="Categorías de tareas",
            description="Listas dinámicas para clasificar tareas (editor visual).",
            value_type="string",
            default=default_categories_json(),
            apply=APPLY_LIVE,
            tier="A",
            section="Tareas",
        ),
        SettingDef(
            key="widgets.task_priorities_json",
            category=CategoryId.WIDGETS,
            label="Prioridades de tareas",
            description="Etiquetas con peso numérico (mayor = más urgente).",
            value_type="string",
            default=default_priorities_json(),
            apply=APPLY_LIVE,
            tier="A",
            section="Tareas",
        ),
        # —— Layout (editor-ready) ——
        SettingDef(
            key="layout.modules_json",
            category=CategoryId.LAYOUT,
            label="Definición de módulos",
            description="JSON de slots (región, orden, visibilidad). Base del editor visual.",
            value_type="string",
            default="",
            apply=APPLY_RELOAD,
            tier="B",
            section="Modelo",
        ),
        # —— Popups / OSD ——
        SettingDef(
            key="popups.edge_margin",
            category=CategoryId.POPUPS,
            label="Margen al borde",
            description="Padding al clamp de popups anclados.",
            value_type="int",
            default=shell_config.POPUP_EDGE_MARGIN,
            config_attr="POPUP_EDGE_MARGIN",
            apply=APPLY_LIVE,
            minimum=0,
            maximum=48,
            step=1,
            tier="B",
            section="Posición",
            unit="px",
        ),
        SettingDef(
            key="popups.volume_osd_hide_ms",
            category=CategoryId.POPUPS,
            label="Duración del OSD de volumen",
            description="Tiempo visible tras el último cambio de volumen.",
            value_type="int",
            default=shell_config.VOLUME_OSD_HIDE_DELAY_MS,
            config_attr="VOLUME_OSD_HIDE_DELAY_MS",
            apply=APPLY_LIVE,
            minimum=400,
            maximum=5000,
            step=100,
            tier="A",
            section="OSD",
            unit="ms",
        ),
        SettingDef(
            key="popups.launcher_width",
            category=CategoryId.POPUPS,
            label="Ancho de Search / Emoji",
            description="Ancho de la tarjeta de Search y Emoji. El portapapeles usa su propio ancho (lista + detalle).",
            value_type="int",
            default=shell_config.LAUNCHER_WIDTH,
            config_attr="LAUNCHER_WIDTH",
            apply=APPLY_RELOAD,
            minimum=320,
            maximum=720,
            step=10,
            tier="B",
            section="Pickers",
            unit="px",
        ),
        # —— Notificaciones ——
        SettingDef(
            key="notificaciones.toasts_enabled",
            category=CategoryId.NOTIFICACIONES,
            label="Mostrar toasts",
            description="Toasts entrantes aparte del historial.",
            value_type="bool",
            default=shell_config.NOTIFICATIONS_TOAST_ENABLED,
            config_attr="NOTIFICATIONS_TOAST_ENABLED",
            apply=APPLY_LIVE,
            tier="A",
            section="Toasts",
        ),
        SettingDef(
            key="notificaciones.sound_enabled",
            category=CategoryId.NOTIFICACIONES,
            label="Sonido de notificación",
            description="Reproduce el audio al recibir una notificación.",
            value_type="bool",
            default=shell_config.NOTIFICATIONS_SOUND_ENABLED,
            config_attr="NOTIFICATIONS_SOUND_ENABLED",
            apply=APPLY_LIVE,
            tier="A",
            section="Toasts",
        ),
        SettingDef(
            key="notificaciones.default_timeout_ms",
            category=CategoryId.NOTIFICACIONES,
            label="Timeout normal",
            description="Auto-cierre de notificaciones normales (0 = persistir).",
            value_type="int",
            default=shell_config.NOTIFICATIONS_DEFAULT_TIMEOUT_MS,
            config_attr="NOTIFICATIONS_DEFAULT_TIMEOUT_MS",
            apply=APPLY_LIVE,
            minimum=0,
            maximum=60000,
            step=500,
            tier="A",
            section="Tiempos",
            unit="ms",
        ),
        SettingDef(
            key="notificaciones.critical_timeout_ms",
            category=CategoryId.NOTIFICACIONES,
            label="Timeout críticas",
            description="Timeout de notificaciones críticas si no persisten.",
            value_type="int",
            default=shell_config.NOTIFICATIONS_CRITICAL_TIMEOUT_MS,
            config_attr="NOTIFICATIONS_CRITICAL_TIMEOUT_MS",
            apply=APPLY_LIVE,
            minimum=0,
            maximum=120000,
            step=1000,
            tier="B",
            section="Tiempos",
            unit="ms",
        ),
        SettingDef(
            key="notificaciones.critical_persist",
            category=CategoryId.NOTIFICACIONES,
            label="Persistir críticas",
            description="Las críticas no se auto-cierran.",
            value_type="bool",
            default=shell_config.NOTIFICATIONS_CRITICAL_PERSIST,
            config_attr="NOTIFICATIONS_CRITICAL_PERSIST",
            apply=APPLY_LIVE,
            tier="B",
            section="Tiempos",
        ),
        SettingDef(
            key="notificaciones.max_visible_toasts",
            category=CategoryId.NOTIFICACIONES,
            label="Toasts visibles",
            description="Máximo de toasts apilados a la vez.",
            value_type="int",
            default=shell_config.NOTIFICATIONS_MAX_VISIBLE_TOASTS,
            config_attr="NOTIFICATIONS_MAX_VISIBLE_TOASTS",
            apply=APPLY_LIVE,
            minimum=1,
            maximum=8,
            step=1,
            tier="B",
            section="Toasts",
        ),
        SettingDef(
            key="notificaciones.max_history",
            category=CategoryId.NOTIFICACIONES,
            label="Historial máximo",
            description="Entradas guardadas en el historial local.",
            value_type="int",
            default=shell_config.NOTIFICATIONS_MAX_HISTORY,
            config_attr="NOTIFICATIONS_MAX_HISTORY",
            apply=APPLY_LIVE,
            minimum=20,
            maximum=1000,
            step=10,
            tier="C",
            section="Historial",
        ),
        SettingDef(
            key="notificaciones.grouping_mode",
            category=CategoryId.NOTIFICACIONES,
            label="Agrupación por defecto",
            description=(
                "Por contacto/título mantiene chats separados (p. ej. WhatsApp). "
                "Por aplicación junta todo lo de esa app."
            ),
            value_type="choice",
            default=shell_config.NOTIFICATIONS_GROUPING_MODE,
            config_attr="NOTIFICATIONS_GROUPING_MODE",
            apply=APPLY_LIVE,
            choices=(
                ("summary", "Por contacto / título"),
                ("app", "Por aplicación"),
            ),
            tier="A",
            section="Agrupación",
        ),
        SettingDef(
            key="notificaciones.grouping_exceptions",
            category=CategoryId.NOTIFICACIONES,
            label="Excepciones de agrupación",
            description=(
                "Apps (separadas por coma) con el modo contrario al por defecto. "
                "Con agrupación por contacto/título, escribe strawberry para "
                "juntar todas las de esa app sin mezclar WhatsApp."
            ),
            value_type="string",
            default=shell_config.NOTIFICATIONS_GROUPING_EXCEPTIONS,
            config_attr="NOTIFICATIONS_GROUPING_EXCEPTIONS",
            apply=APPLY_LIVE,
            tier="A",
            section="Agrupación",
        ),
        # —— Multimedia ——
        SettingDef(
            key="multimedia.position_poll_ms",
            category=CategoryId.MULTIMEDIA,
            label="Poll de posición",
            description="Cada cuánto se consulta la posición MPRIS.",
            value_type="int",
            default=shell_config.MEDIA_POSITION_POLL_MS,
            config_attr="MEDIA_POSITION_POLL_MS",
            apply=APPLY_RELOAD,
            minimum=250,
            maximum=5000,
            step=250,
            tier="C",
            section="MPRIS",
            unit="ms",
        ),
        SettingDef(
            key="multimedia.artwork_size",
            category=CategoryId.MULTIMEDIA,
            label="Tamaño de carátula",
            description="Tamaño del artwork en el popup de media.",
            value_type="int",
            default=shell_config.MEDIA_ARTWORK_SIZE,
            config_attr="MEDIA_ARTWORK_SIZE",
            apply=APPLY_RELOAD,
            minimum=64,
            maximum=256,
            step=8,
            tier="B",
            section="Popup",
            unit="px",
        ),
        SettingDef(
            key="multimedia.visualizer_fps",
            category=CategoryId.MULTIMEDIA,
            label="FPS del visualizador",
            description="Frecuencia de refresco del espectro de audio.",
            value_type="int",
            default=shell_config.AUDIO_VISUALIZER_FPS,
            config_attr="AUDIO_VISUALIZER_FPS",
            apply=APPLY_RESTART,
            minimum=8,
            maximum=30,
            step=1,
            tier="C",
            section="Visualizador",
        ),
        # —— Estadísticas ——
        SettingDef(
            key="estadisticas.update_interval_sec",
            category=CategoryId.ESTADISTICAS,
            label="Intervalo de actualización",
            description="Frecuencia de muestreo de CPU/RAM/GPU.",
            value_type="float",
            default=float(shell_config.SYSTEM_STATS_UPDATE_INTERVAL),
            config_attr="SYSTEM_STATS_UPDATE_INTERVAL",
            apply=APPLY_RELOAD,
            minimum=0.5,
            maximum=5.0,
            step=0.5,
            tier="A",
            section="Sensores",
            unit="s",
        ),
        # —— IA ——
        SettingDef(
            key="ia.enabled",
            category=CategoryId.IA,
            label="IA en recordatorios",
            description="Usar llama-cli para frases de recordatorio/briefing.",
            value_type="bool",
            default=shell_config.TASK_WATCHER_AI_ENABLED,
            config_attr="TASK_WATCHER_AI_ENABLED",
            apply=APPLY_RESTART,
            tier="A",
            section="General",
        ),
        SettingDef(
            key="ia.model_path",
            category=CategoryId.IA,
            label="Ruta del modelo",
            description="Archivo GGUF para llama-cli.",
            value_type="path",
            default=shell_config.TASK_WATCHER_AI_MODEL_PATH,
            config_attr="TASK_WATCHER_AI_MODEL_PATH",
            apply=APPLY_RESTART,
            tier="A",
            section="Modelo",
        ),
        SettingDef(
            key="ia.binary",
            category=CategoryId.IA,
            label="Binario",
            description="Comando o ruta de llama-cli.",
            value_type="string",
            default=shell_config.TASK_WATCHER_AI_BINARY,
            config_attr="TASK_WATCHER_AI_BINARY",
            apply=APPLY_RESTART,
            tier="B",
            section="Modelo",
        ),
        SettingDef(
            key="ia.context_size",
            category=CategoryId.IA,
            label="Contexto (-c)",
            description="Tokens de contexto del modelo.",
            value_type="int",
            default=shell_config.TASK_WATCHER_AI_CONTEXT_SIZE,
            config_attr="TASK_WATCHER_AI_CONTEXT_SIZE",
            apply=APPLY_RESTART,
            minimum=256,
            maximum=8192,
            step=256,
            tier="C",
            section="Avanzado",
        ),
        SettingDef(
            key="ia.max_tokens",
            category=CategoryId.IA,
            label="Máx. tokens (-n)",
            description="Longitud máxima de generación en recordatorios.",
            value_type="int",
            default=shell_config.TASK_WATCHER_AI_MAX_TOKENS,
            config_attr="TASK_WATCHER_AI_MAX_TOKENS",
            apply=APPLY_RESTART,
            minimum=8,
            maximum=256,
            step=8,
            tier="C",
            section="Avanzado",
        ),
        SettingDef(
            key="ia.timeout_sec",
            category=CategoryId.IA,
            label="Timeout",
            description="Segundos máximos por invocación de llama-cli.",
            value_type="int",
            default=shell_config.TASK_WATCHER_AI_TIMEOUT_SEC,
            config_attr="TASK_WATCHER_AI_TIMEOUT_SEC",
            apply=APPLY_RESTART,
            minimum=5,
            maximum=120,
            step=5,
            tier="C",
            section="Avanzado",
            unit="s",
        ),
        SettingDef(
            key="ia.ngl",
            category=CategoryId.IA,
            label="Capas GPU (-ngl)",
            description="Offload a GPU. 99 ≈ todas las capas.",
            value_type="int",
            default=shell_config.TASK_WATCHER_AI_NGL,
            config_attr="TASK_WATCHER_AI_NGL",
            apply=APPLY_RESTART,
            minimum=0,
            maximum=99,
            step=1,
            tier="C",
            section="Avanzado",
        ),
        SettingDef(
            key="ia.startup_briefing",
            category=CategoryId.IA,
            label="Briefing al iniciar",
            description="Notificación de resumen de tareas al arrancar Jugoo.",
            value_type="bool",
            default=shell_config.TASK_STARTUP_BRIEFING_ENABLED,
            config_attr="TASK_STARTUP_BRIEFING_ENABLED",
            apply=APPLY_RESTART,
            tier="A",
            section="General",
        ),
        SettingDef(
            key="ia.watcher_enabled",
            category=CategoryId.IA,
            label="Vigilante de tareas",
            description="Proceso en segundo plano para recordatorios.",
            value_type="bool",
            default=shell_config.TASK_WATCHER_ENABLED,
            config_attr="TASK_WATCHER_ENABLED",
            apply=APPLY_RESTART,
            tier="A",
            section="General",
        ),
        # —— Modo noche ——
        SettingDef(
            key="modo_noche.enabled",
            category=CategoryId.MODO_NOCHE,
            label="Activar modo noche",
            description="Aplica temperatura cálida a la pantalla (hyprsunset/gammastep).",
            value_type="bool",
            default=False,
            apply=APPLY_LIVE,
            tier="A",
            section="Control",
        ),
        SettingDef(
            key="modo_noche.temperature",
            category=CategoryId.MODO_NOCHE,
            label="Temperatura",
            description="Temperatura de color en Kelvin (más bajo = más cálido).",
            value_type="int",
            default=4500,
            apply=APPLY_LIVE,
            minimum=2500,
            maximum=6500,
            step=100,
            tier="A",
            section="Control",
            unit="K",
        ),
        SettingDef(
            key="modo_noche.auto_schedule",
            category=CategoryId.MODO_NOCHE,
            label="Horario automático",
            description="Activa/desactiva según hora de inicio y fin.",
            value_type="bool",
            default=False,
            apply=APPLY_LIVE,
            tier="A",
            section="Horario",
        ),
        SettingDef(
            key="modo_noche.start_hour",
            category=CategoryId.MODO_NOCHE,
            label="Hora de inicio",
            description="Hora local (0–23) para encender el modo noche.",
            value_type="int",
            default=21,
            apply=APPLY_LIVE,
            minimum=0,
            maximum=23,
            step=1,
            tier="A",
            section="Horario",
        ),
        SettingDef(
            key="modo_noche.end_hour",
            category=CategoryId.MODO_NOCHE,
            label="Hora de fin",
            description="Hora local (0–23) para apagar el modo noche.",
            value_type="int",
            default=7,
            apply=APPLY_LIVE,
            minimum=0,
            maximum=23,
            step=1,
            tier="A",
            section="Horario",
        ),
        # —— Comportamiento ——
        SettingDef(
            key="comportamiento.workspace_hover_delay_ms",
            category=CategoryId.COMPORTAMIENTO,
            label="Retraso hover workspaces",
            description="Espera antes de abrir el panel de workspace.",
            value_type="int",
            default=shell_config.WORKSPACE_HOVER_DELAY_MS,
            config_attr="WORKSPACE_HOVER_DELAY_MS",
            apply=APPLY_LIVE,
            minimum=0,
            maximum=1000,
            step=50,
            tier="B",
            section="Workspaces",
            unit="ms",
        ),
        SettingDef(
            key="comportamiento.clipboard_history_limit",
            category=CategoryId.COMPORTAMIENTO,
            label="Límite historial portapapeles",
            description="Entradas máximas en el historial local de Jugoo (no afecta al clipboard del sistema).",
            value_type="int",
            default=shell_config.CLIPBOARD_HISTORY_LIMIT,
            config_attr="CLIPBOARD_HISTORY_LIMIT",
            apply=APPLY_LIVE,
            minimum=20,
            maximum=500,
            step=10,
            tier="B",
            section="Portapapeles",
        ),
        SettingDef(
            key="comportamiento.clipboard_max_text_bytes",
            category=CategoryId.COMPORTAMIENTO,
            label="Texto máximo por entrada",
            description="Bytes UTF-8 máximos por texto en el historial. Más grande se descarta del historial.",
            value_type="int",
            default=shell_config.CLIPBOARD_MAX_TEXT_BYTES,
            config_attr="CLIPBOARD_MAX_TEXT_BYTES",
            apply=APPLY_RESTART,
            minimum=64 * 1024,
            maximum=8 * 1024 * 1024,
            step=64 * 1024,
            tier="B",
            section="Portapapeles",
            unit="B",
        ),
        SettingDef(
            key="comportamiento.clipboard_max_history_bytes",
            category=CategoryId.COMPORTAMIENTO,
            label="Tamaño total del historial",
            description="Presupuesto total (texto + imágenes) del historial local de Jugoo.",
            value_type="int",
            default=shell_config.CLIPBOARD_MAX_HISTORY_BYTES,
            config_attr="CLIPBOARD_MAX_HISTORY_BYTES",
            apply=APPLY_RESTART,
            minimum=5 * 1024 * 1024,
            maximum=200 * 1024 * 1024,
            step=1 * 1024 * 1024,
            tier="B",
            section="Portapapeles",
            unit="B",
        ),
        SettingDef(
            key="comportamiento.emoji_columns",
            category=CategoryId.COMPORTAMIENTO,
            label="Columnas del grid de emoji",
            description="Ancho del grid del picker de emoji.",
            value_type="int",
            default=shell_config.EMOJI_PICKER_COLUMNS,
            config_attr="EMOJI_PICKER_COLUMNS",
            apply=APPLY_RELOAD,
            minimum=6,
            maximum=12,
            step=1,
            tier="B",
            section="Emoji",
        ),
        # —— Avanzado ——
        SettingDef(
            key="avanzado.ai_threads",
            category=CategoryId.AVANZADO,
            label="Hilos IA (-t)",
            description="Hilos CPU para llama-cli.",
            value_type="int",
            default=shell_config.TASK_WATCHER_AI_THREADS,
            config_attr="TASK_WATCHER_AI_THREADS",
            apply=APPLY_RESTART,
            minimum=1,
            maximum=16,
            step=1,
            tier="C",
            section="IA",
        ),
        SettingDef(
            key="avanzado.ai_batch",
            category=CategoryId.AVANZADO,
            label="Batch IA (-b)",
            description="Tamaño de batch de inferencia.",
            value_type="int",
            default=shell_config.TASK_WATCHER_AI_BATCH_SIZE,
            config_attr="TASK_WATCHER_AI_BATCH_SIZE",
            apply=APPLY_RESTART,
            minimum=8,
            maximum=512,
            step=8,
            tier="C",
            section="IA",
        ),
        SettingDef(
            key="avanzado.audio_poll_sec",
            category=CategoryId.AVANZADO,
            label="Poll de audio",
            description="Intervalo del servicio de volumen/streams.",
            value_type="float",
            default=float(shell_config.AUDIO_POLL_INTERVAL_SEC),
            config_attr="AUDIO_POLL_INTERVAL_SEC",
            apply=APPLY_RESTART,
            minimum=0.2,
            maximum=2.0,
            step=0.1,
            tier="C",
            section="Audio",
            unit="s",
        ),
    )


def settings_by_key(catalog: tuple[SettingDef, ...] | None = None) -> dict[str, SettingDef]:
    items = catalog if catalog is not None else build_settings_catalog()
    return {item.key: item for item in items}


def settings_for_category(
    category: CategoryId,
    catalog: tuple[SettingDef, ...] | None = None,
) -> tuple[SettingDef, ...]:
    items = catalog if catalog is not None else build_settings_catalog()
    return tuple(item for item in items if item.category is category)


DefaultFactory = Callable[[], Any]
