-- Generated by Jugoo from themes/space.toml. Do not edit.
local function apply()
    hl.config({
        general = {
            col = {
                active_border = { colors = { "rgba(7c8cffff)", "rgba(d946efff)" }, angle = 45 },
                inactive_border = "rgba(29345cff)",
            },
        },
        group = {
            col = {
                border_active = "rgba(7c8cffff)",
                border_inactive = "rgba(29345cff)",
                border_locked_active = "rgba(8b5cf6ff)",
                border_locked_inactive = "rgba(29345cff)",
            },
            groupbar = {
                col = {
                    active = "rgba(d946efff)",
                    inactive = "rgba(29345cff)",
                    locked_active = "rgba(8b5cf6ff)",
                    locked_inactive = "rgba(29345cff)",
                },
            },
        },
        decoration = {
            rounding = 12,
            active_opacity = 0.94,
            inactive_opacity = 0.85,
            fullscreen_opacity = 1,
            blur = {
                enabled = true,
                size = 8,
                passes = 4,
                special = true,
            },
        },
    })
end

return { apply = apply }
